# Generated by Django 5.2.1 on 2025-05-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(choices=[('M', 'Married'), ('U', 'Un-Married'), ('W', 'Widow/Widower'), ('D', 'Divorced')], default='U', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='other_email',
            field=models.EmailField(default='avshankar9151@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification',
            field=models.CharField(choices=[('IL', 'Illiterate'), ('NMT', 'Non-Matric'), ('MT', 'Matric'), ('SSC', 'Senior-Secondary'), ('UG', 'Undergraduate/Graduate'), ('PG', 'Postgraduate'), ('DOC', 'Doctorate'), ('TEC', 'Technical (Professional)')], default='UG', max_length=3),
            preserve_default=False,
        ),
    ]
